In [2]:
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [6]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [96]:
x = iris.data
y = iris.target

In [97]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [98]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
x_train,y_train,x_test,y_test = train_test_split(x,y,shuffle=True)


#test_size=ratio of devision
#if test size =0.33 then 70%  od data goes to training and remaining goes for testing
#shuffle = True

In [101]:
x_train

array([[5.4, 3. , 4.5, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 2.7, 4.1, 1. ],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.9, 3.6, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [6.9, 3.1, 5.1, 2.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2.8, 5.1, 2.4],
       [4.4, 3. , 1.3, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [6.3, 2.5, 5. , 1.9],
       [5. , 2. , 3.5, 1. ],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [4.9, 3.6, 1.4, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [4.6, 3.2, 1.4, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.6, 4. , 1.2],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5.8, 2.7, 3.9, 1.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3

In [102]:
x_test

array([1, 0, 1, 0, 0, 2, 1, 1, 2, 0, 0, 0, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 2, 1, 1, 0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 2, 2, 2, 0,
       1, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0,
       2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 0, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 0, 1, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 0,
       0, 2])

In [103]:
x_train[0]

array([5.4, 3. , 4.5, 1.5])

In [104]:
x_test[0]

1

In [105]:
from sklearn.linear_model import LinearRegression

The Iris Dataset contains four features (length and width of sepals and petals) of 50 samples of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). ... The dataset is often used in data mining, classification and clustering examples and to test algorithms.

In [106]:
model = LinearRegression()

In [107]:
model.fit(x_train,x_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [108]:
x.shape

(150, 4)

In [109]:
y.shape

(150,)

In [110]:
len(x_train)

112

In [111]:
len(x_test)

112

In [112]:
len(y_train)
x = x.reshape(-1,1)

In [116]:
x_test

array([1, 0, 1, 0, 0, 2, 1, 1, 2, 0, 0, 0, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 2, 1, 1, 0, 2, 1, 0, 0, 2, 2, 1, 1, 2, 2, 2, 2, 0,
       1, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0,
       2, 0, 2, 2, 2, 1, 0, 1, 0, 2, 0, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 0, 1, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 0,
       0, 2])

In [117]:
x_train

array([[5.4, 3. , 4.5, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 2.7, 4.1, 1. ],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.9, 3.6, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [6.9, 3.1, 5.1, 2.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2.8, 5.1, 2.4],
       [4.4, 3. , 1.3, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [6.3, 2.5, 5. , 1.9],
       [5. , 2. , 3.5, 1. ],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [4.9, 3.6, 1.4, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [4.6, 3.2, 1.4, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.8, 2.6, 4. , 1.2],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5.8, 2.7, 3.9, 1.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3

In [118]:
model.predict(x_train)

array([ 1.42919588e+00, -7.76582788e-02,  1.00793996e+00, -2.97491426e-02,
       -2.93600452e-02,  1.79195180e+00,  1.06760747e+00,  9.18703030e-01,
        1.85513147e+00,  2.65351231e-02,  3.51849798e-02, -1.01284342e-01,
        1.93642241e+00,  2.04867169e+00, -2.20481889e-05,  1.44084436e+00,
        2.16953205e-01,  1.69191302e+00,  9.69788194e-01,  1.59629646e-01,
       -3.11229406e-02,  1.61037624e+00, -1.07262559e-01, -1.17421947e-01,
       -5.74138289e-02,  1.30671899e+00, -3.92330801e-03,  1.60590003e+00,
        1.09839359e+00,  1.35299415e+00, -1.38691141e-01,  1.83699734e+00,
        1.07001893e+00, -3.06032937e-02, -1.47251574e-02,  1.60412421e+00,
        1.61524765e+00,  1.23486972e+00,  1.28739009e+00,  2.26032411e+00,
        2.23377915e+00,  2.04446858e+00,  1.69250770e+00, -4.09546385e-02,
        1.04288070e+00,  1.76955606e+00,  6.22926595e-03,  2.06684529e+00,
       -1.74513900e-02,  1.18586152e+00,  9.10046359e-01,  2.01875193e+00,
        1.20707541e+00,  

In [119]:
import pickle
with open('iris_classifier.pkl','wb') as f:
  pickle.dump(model,f)

In [120]:
f

<_io.BufferedWriter name='iris_classifier.pkl'>